<h1>numpy</h1>

<h2>Creating a numpy array</h2>

In [1]:
import numpy as np
ax = np.array([1,2,3,4,5])
print(x,id(x),len(x))

NameError: name 'x' is not defined

<h2>Specifying the type</h2>
<h3>Useful when reading a text stream directly into a numerical array</h3>

In [ ]:
x=['1','2','3']
xi = np.array(x,'int')
xf = np.array(x,'float')
xs = np.array(x,'str')
print(xi,xf,xs,sep='\n')

<h2>Basic operations</h2>

In [ ]:
x = np.array([13,24,21.2,17.6,21.7],'float')
print(x.sum(),x.mean(),x.std(),sep='\n')

<h2>Multi-dimensional arrays</h2>

In [2]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
print(ax)

[[  0.   1.   2.   3.   4.   5.]
 [ 10.  11.  12.  13.  14.  15.]
 [ 20.  21.  22.  23.  24.  25.]]


<h3>Indexing</h3>

In [3]:
ax[1,3] #indexing

13.0

<h3>Slicing</h3>

In [4]:
ax[1:3,2:4]
#ax[:,2:]

array([[ 12.,  13.],
       [ 22.,  23.]])

<h3>Reshaping</h3>


In [5]:
print(ax.shape)
ax.reshape(9,2)
#ax.reshape(10,3)

(3, 6)


array([[  0.,   1.],
       [  2.,   3.],
       [  4.,   5.],
       [ 10.,  11.],
       [ 12.,  13.],
       [ 14.,  15.],
       [ 20.,  21.],
       [ 22.,  23.],
       [ 24.,  25.]])

<h3>Creating initialized arrays</h3>

In [6]:
ax = np.arange(10)
print(ax)
ay = np.array([np.arange(10),np.arange(10)])
print(ay)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [7]:
ay = np.array([np.arange(2,10),np.arange(10)])
print(ay)
ay = np.array([np.arange(2,10,2),np.arange(10)])
print(ay)

[array([2, 3, 4, 5, 6, 7, 8, 9]) array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]
[array([2, 4, 6, 8]) array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]


In [8]:
ax = np.ones(10)
print(ax)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [9]:
ax = np.arange(10)**2
print(ax)

[ 0  1  4  9 16 25 36 49 64 81]


In [10]:
np.identity(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

<h3>Matrix multiplication</h3>


In [11]:
ax = np.arange(10)
ay = np.array([ax,ax])
#Scalar multiplication
ay*2

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [12]:
ay.shape

(2, 10)

In [13]:
np.dot(ay,ay.reshape(10,2)) #Dot product

array([[220, 265],
       [220, 265]])

<h3>Comparing numpy arrays with lists</h3>

In [14]:
n=10
ax = np.array([np.arange(n)**2,np.arange(n)**3])
ay = ax.transpose()
print(ax)
print(ay)
np.dot(ax,ay)

[[  0   1   4   9  16  25  36  49  64  81]
 [  0   1   8  27  64 125 216 343 512 729]]
[[  0   0]
 [  1   1]
 [  4   8]
 [  9  27]
 [ 16  64]
 [ 25 125]
 [ 36 216]
 [ 49 343]
 [ 64 512]
 [ 81 729]]


array([[ 15333, 120825],
       [120825, 978405]], dtype=int32)

<h4>Functionalize this</h4>


In [15]:
def dotproduct(n):
    ax = np.array([np.arange(n)**2,np.arange(n)**3])
    ay = ax.transpose()
    import datetime
    start = datetime.datetime.now()
    np.dot(ax,ay)
    end = datetime.datetime.now()
    return end-start
    
dotproduct(10)    

datetime.timedelta(0, 0, 500)

<h4>Do the same with python lists</h4>


In [16]:

def dot_product_lists(n):
    x = [x**2 for x in range(n)]
    y = [x**3 for x in range(n)]
    ax = [x,y]
    ay = [list(i) for i in zip(*ax)]
    import datetime
    start = datetime.datetime.now()
    [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*ay)] for X_row in ax]
    end = datetime.datetime.now()
    return end-start
    
dot_product_lists(10000)

datetime.timedelta(0, 0, 20120)

In [18]:
for n in [10,100,1000,10000]:
    numpy_result = dotproduct(n)
    list_result = dot_product_lists(n)
    print(n,numpy_result,list_result,sep='\t')

10	0:00:00	0:00:00
100	0:00:00	0:00:00.001001
1000	0:00:00	0:00:00.001001
10000	0:00:00	0:00:00.019019


<h3>Selecting elements from an np array</h3>

In [20]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
print(ax)
np.where(ax%2==0,1,0)

[[  0.   1.   2.   3.   4.   5.]
 [ 10.  11.  12.  13.  14.  15.]
 [ 20.  21.  22.  23.  24.  25.]]


array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]])

In [21]:

#linalg, a linear algebra module
#functions dealing with polynomials, differentials, etc


In [22]:
import scipy
scipy.nanmean(x)

12.5

<h3>Random number support in numpy</h3>

In [23]:
np.random.normal(size=10)
#np.random.normal(size=(100,100))
#np.random.exponential()
#np.random.exponential(1.0,size=(6,3))
#np.random.randint(-10,10,size=(9,9))

array([-1.31165099,  1.16979064,  0.90011396,  1.30558534, -0.39220693,
       -2.20538745,  1.23488517,  0.40539313, -1.01291141,  0.0370808 ])

In [24]:
    x = [['0','1','2','3'],['4','5','6','7'],['8','9','10','11']]
    ax=np.array(x,int)
    ax.reshape(4,3)
    ax.reshape(6,2)
    print(ax[2,2])

10


In [27]:
from numpy import pi
x = np.linspace( 0, 2*pi, 100 )
f = np.sin(x)
print(np.ceil(f.max() -f.min()))

2.0


In [31]:
a = np.arange(12)
b = a
c = a.view()
d = a.copy()
c[0]=12
print(a,b,c,d,sep='\n')

[12  1  2  3  4  5  6  7  8  9 10 11]
[12  1  2  3  4  5  6  7  8  9 10 11]
[12  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [42]:
# Which of the following should be put into the blank 
#to find the closest value (to a given scalar) in an array?

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).max()
#print(Z[index])
index = (np.abs(Z-v)).argmax()
print(Z[index])
index = (np.abs(Z-v)).min()
#print(Z[index])
index = (np.abs(Z-v)).argmin()
print(Z[index])
v

99
12


12.08097874284645

In [43]:
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
  print(0 * np.nan)
  print(np.nan == np.nan)
  print(np.inf > np.nan)
  print(np.nan - np.nan)
  print(0.3 == 3 * 0.1)
  print(0.3 == 3. * 0.1)

nan
False
False
nan
False
False


In [63]:
a=np.arange(6)
a = np.array([a,a+10,a+20,a+30,a+40,a+50])
#print(a)

print(a[(0,1,2,3,4),(1,2,3,4,5)])

print(a[3:,[0,2,5]])
mask = np.array([1,0,1,0,0,1],dtype = bool)

print(a[mask,2])

[ 1 12 23 34 45]
[[30 32 35]
 [40 42 45]
 [50 52 55]]
[ 2 22 52]


In [66]:
#Fill in the blank to create a random vector of size 10 and sort it
Z = np.random.random(10)
#Z.______

print(Z)
"""
 Please follow the instructions to answer the question: 
      1.Delete every blank space that is not necessary (e.g., x==y not x == y)
      2.You only need to fill in the blank
      3.Use single quotes only if it is necessary
"""
Z.sort()

print(Z)

[ 0.4180958   0.85189624  0.98456502  0.15249481  0.97941628  0.68324183
  0.5064401   0.13813332  0.64203808  0.11091472]
[ 0.11091472  0.13813332  0.15249481  0.4180958   0.5064401   0.64203808
  0.68324183  0.85189624  0.97941628  0.98456502]


In [77]:
#Fill in the blank to find the nearest value from a given value in an array
Z = np.random.uniform(0,1,10)
print(Z)
q = 0.5 
m = Z.flat[(np.abs(Z-q)).argmin()]
m = Z.flat[(np.abs(Z-q)).argmin()]
print(m)

[ 0.02511782  0.82469889  0.83190159  0.3150631   0.34609476  0.36783831
  0.82612044  0.73194664  0.1710921   0.61046625]
0.61046625435
